---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80
        volumeMounts:
          - name: webpage
            mountPath: /usr/share/nginx/html
      volumes:
        - name: webpage
          configMap:
            name: nginx-webpage

# vim: set ts=2 sw=2 et:
